name: Rebase
on:
  pull_request_target:
    types: [created, labeled, opened, reopened]
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --rebase main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
