name: Rebase
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  add-comment:
    if: startsWith(github.head_ref, 'migrate-nx-to-')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.AUTOREBASE_TOKEN}}
