name: Rebase
on:
  pull_request_target:
    types: [created, opened, reopened]
jobs:
  rebase:
    name: Rebase
    if: startsWith(github.head_ref, 'migrate-nx-to-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
      - name: Echo
        run: echo "AUTO REBASE 0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
