name: Automatic Rebase and merge NX PRs
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  rebase:
    name: Rebase and merge
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'migrate-nx-to-')
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        if: ${{ contains(github.event.pull_request.title, 'rebase')}}
        uses: cirrus-actions/rebase@1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto Approve
        uses: actions/github-script@v4
        with:
          script: |
            const result = await github.pulls.createReview({
            owner: github.repository_owner,
            repo: github.repository_owner,
            pull_number: context.issue.number,
            event: "APPROVE"
            })
      - name: Enable auto-merge for NX PRs
        if: ${{ contains(github.event.pull_request.title, 'rebase')}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Echo
        run: echo "AUTO REBASE 0"
