name: Rebase
on:
  pull_request_target:
    types: [created, labeled, opened, reopened]
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --rebase main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
