name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Label
      uses: actions/labeler@v5
    - name: AUTO REBASE
      uses: Label305/AutoRebase@v0.1
      with:
        github_token: ${{ secrets.AUTOREBASE_TOKEN }}
    - name: Check if PR exists
      id: check
      run: gh pr list
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
