name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Label
      uses: actions/labeler@v5
    - name: AUTO REBASE
      uses: Label305/AutoRebase@v0.1
      with:
        github_token: ${{ secrets.AUTOREBASE_TOKEN }}
    - name: Checkout the latest code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - name: Check if at least one PR exists
      id: check-prs
      run: |
        gh pr list
        prs=$(gh pr list --json state -q 'length')
        echo Size of PRS ARRAY: $prs
        prs1=$(gh pr list --author "dependabot[bot]" --json url)
        echo PRS1 ARRAY: $prs1
        for i in "${prs1[@]}"
        do
          echo "$i"
          #echo "${prs1[$i]}"
          echo "${prs1[1]}"
        done
        echo "exists=true" >> "$GITHUB_OUTPUT"
        if ((prs > 0)); then
          echo "exist=true" >> "$GITHUB_OUTPUT"
        fi
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Found PRs
      if: 'steps.check-prs.outputs.exists'
      run: echo Found at least one PR
